name = "your-app-name"
main = "src/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "d1-demo"
database_id = "e1908a86-0e79-47d1-bb8c-8a331b00976e"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "r2-demo"