name = "apiservice"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

main = "src/index.ts"

[build]
command = "pnpm run build"

[[r2_buckets]]
bucket_name = ""
preview_bucket_name = ""
binding = ""

[[d1_databases]]
binding = "DB"
database_name = ""
database_id = ""


# You can use wrangler to set secrets and environments to keep your secrets out of your codebase.
[vars]
WRANGLER_BUILD_CONDITIONS=""
WRANGLER_BUILD_PLATFORM="node"
CLERK_PUBLISHABLE_KEY = ""
CLERK_SECRET_KEY = ""

[dev]
port = 8787


