name = "apiservice"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

main = "src/index.ts"

[build]
command = "pnpm run build"

[[r2_buckets]]
bucket_name = "r2-demo"
preview_bucket_name = ""
binding = "BUCKET"

[[d1_databases]]
binding = "DB"
database_name = "d1-demo"
database_id = "e1908a86-0e79-47d1-bb8c-8a331b00976e"


# You can use wrangler to set secrets and environments to keep your secrets out of your codebase.
[vars]
WRANGLER_BUILD_CONDITIONS=""
WRANGLER_BUILD_PLATFORM="node"
CLERK_PUBLISHABLE_KEY = ""
CLERK_SECRET_KEY = ""

[dev]
port = 8787


